- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  when: not ansible_check_mode

- name: Reload ufw
  ansible.builtin.ufw:
    state: reloaded